"""Smoke tests for src/webprobe/capturer.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_capturer():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.capturer")
    assert mod is not None

def test_capture_site_is_callable():
    """Function capture_site exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.capturer")
    fn = getattr(mod, "capture_site", None)
    assert fn is not None, "'capture_site' not found in webprobe.capturer"
    assert callable(fn)
