"""Smoke tests for src/webprobe/analyzer.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_analyzer():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.analyzer")
    assert mod is not None

def test_analyze_is_callable():
    """Function analyze exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.analyzer")
    fn = getattr(mod, "analyze", None)
    assert fn is not None, "'analyze' not found in webprobe.analyzer"
    assert callable(fn)
