"""Smoke tests for src/webprobe/visual.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_visual():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.visual")
    assert mod is not None

def test_contrast_ratio_is_callable():
    """Function contrast_ratio exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.visual")
    fn = getattr(mod, "contrast_ratio", None)
    assert fn is not None, "'contrast_ratio' not found in webprobe.visual"
    assert callable(fn)

def test_check_wcag_aa_is_callable():
    """Function check_wcag_aa exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.visual")
    fn = getattr(mod, "check_wcag_aa", None)
    assert fn is not None, "'check_wcag_aa' not found in webprobe.visual"
    assert callable(fn)

def test_check_wcag_aaa_is_callable():
    """Function check_wcag_aaa exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.visual")
    fn = getattr(mod, "check_wcag_aaa", None)
    assert fn is not None, "'check_wcag_aaa' not found in webprobe.visual"
    assert callable(fn)

def test_check_contrast_from_page_is_callable():
    """Function check_contrast_from_page exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.visual")
    fn = getattr(mod, "check_contrast_from_page", None)
    assert fn is not None, "'check_contrast_from_page' not found in webprobe.visual"
    assert callable(fn)

def test_detect_hidden_elements_is_callable():
    """Function detect_hidden_elements exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.visual")
    fn = getattr(mod, "detect_hidden_elements", None)
    assert fn is not None, "'detect_hidden_elements' not found in webprobe.visual"
    assert callable(fn)

def test_analyze_screenshot_is_callable():
    """Function analyze_screenshot exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.visual")
    fn = getattr(mod, "analyze_screenshot", None)
    assert fn is not None, "'analyze_screenshot' not found in webprobe.visual"
    assert callable(fn)
