"""Smoke tests for src/webprobe/models.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_models():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.models")
    assert mod is not None
