"""Smoke tests for src/webprobe/differ.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_differ():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.differ")
    assert mod is not None

def test_load_run_is_callable():
    """Function load_run exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.differ")
    fn = getattr(mod, "load_run", None)
    assert fn is not None, "'load_run' not found in webprobe.differ"
    assert callable(fn)

def test_diff_runs_is_callable():
    """Function diff_runs exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.differ")
    fn = getattr(mod, "diff_runs", None)
    assert fn is not None, "'diff_runs' not found in webprobe.differ"
    assert callable(fn)
