"""Smoke tests for src/webprobe/browser.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_browser():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.browser")
    assert mod is not None
