"""Smoke tests for src/webprobe/security.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_security():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    assert mod is not None

def test_check_security_headers_is_callable():
    """Function check_security_headers exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    fn = getattr(mod, "check_security_headers", None)
    assert fn is not None, "'check_security_headers' not found in webprobe.security"
    assert callable(fn)

def test_check_cookies_is_callable():
    """Function check_cookies exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    fn = getattr(mod, "check_cookies", None)
    assert fn is not None, "'check_cookies' not found in webprobe.security"
    assert callable(fn)

def test_check_mixed_content_is_callable():
    """Function check_mixed_content exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    fn = getattr(mod, "check_mixed_content", None)
    assert fn is not None, "'check_mixed_content' not found in webprobe.security"
    assert callable(fn)

def test_check_cors_is_callable():
    """Function check_cors exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    fn = getattr(mod, "check_cors", None)
    assert fn is not None, "'check_cors' not found in webprobe.security"
    assert callable(fn)

def test_check_information_disclosure_is_callable():
    """Function check_information_disclosure exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    fn = getattr(mod, "check_information_disclosure", None)
    assert fn is not None, "'check_information_disclosure' not found in webprobe.security"
    assert callable(fn)

def test_check_forms_is_callable():
    """Function check_forms exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    fn = getattr(mod, "check_forms", None)
    assert fn is not None, "'check_forms' not found in webprobe.security"
    assert callable(fn)

def test_check_xss_signals_is_callable():
    """Function check_xss_signals exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    fn = getattr(mod, "check_xss_signals", None)
    assert fn is not None, "'check_xss_signals' not found in webprobe.security"
    assert callable(fn)

def test_scan_capture_is_callable():
    """Function scan_capture exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    fn = getattr(mod, "scan_capture", None)
    assert fn is not None, "'scan_capture' not found in webprobe.security"
    assert callable(fn)

def test_scan_graph_is_callable():
    """Function scan_graph exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.security")
    fn = getattr(mod, "scan_graph", None)
    assert fn is not None, "'scan_graph' not found in webprobe.security"
    assert callable(fn)
