"""Smoke tests for src/webprobe/llm_provider.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_llm_provider():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.llm_provider")
    assert mod is not None

def test_create_provider_is_callable():
    """Function create_provider exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.llm_provider")
    fn = getattr(mod, "create_provider", None)
    assert fn is not None, "'create_provider' not found in webprobe.llm_provider"
    assert callable(fn)

def test_transmogrify_prompt_is_callable():
    """Function transmogrify_prompt exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.llm_provider")
    fn = getattr(mod, "transmogrify_prompt", None)
    assert fn is not None, "'transmogrify_prompt' not found in webprobe.llm_provider"
    assert callable(fn)
