"""Smoke tests for src/webprobe/mask.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_mask():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.mask")
    assert mod is not None

def test_load_mask_is_callable():
    """Function load_mask exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.mask")
    fn = getattr(mod, "load_mask", None)
    assert fn is not None, "'load_mask' not found in webprobe.mask"
    assert callable(fn)

def test_apply_mask_is_callable():
    """Function apply_mask exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.mask")
    fn = getattr(mod, "apply_mask", None)
    assert fn is not None, "'apply_mask' not found in webprobe.mask"
    assert callable(fn)
