"""Smoke tests for src/webprobe/frameworks.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_frameworks():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.frameworks")
    assert mod is not None

def test_detect_astro_is_callable():
    """Function detect_astro exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.frameworks")
    fn = getattr(mod, "detect_astro", None)
    assert fn is not None, "'detect_astro' not found in webprobe.frameworks"
    assert callable(fn)

def test_detect_nextjs_is_callable():
    """Function detect_nextjs exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.frameworks")
    fn = getattr(mod, "detect_nextjs", None)
    assert fn is not None, "'detect_nextjs' not found in webprobe.frameworks"
    assert callable(fn)

def test_detect_sveltekit_is_callable():
    """Function detect_sveltekit exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.frameworks")
    fn = getattr(mod, "detect_sveltekit", None)
    assert fn is not None, "'detect_sveltekit' not found in webprobe.frameworks"
    assert callable(fn)

def test_detect_framework_is_callable():
    """Function detect_framework exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.frameworks")
    fn = getattr(mod, "detect_framework", None)
    assert fn is not None, "'detect_framework' not found in webprobe.frameworks"
    assert callable(fn)
