"""Smoke tests for src/webprobe/explorer.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_explorer():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.explorer")
    assert mod is not None

def test_explore_site_is_callable():
    """Function explore_site exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.explorer")
    fn = getattr(mod, "explore_site", None)
    assert fn is not None, "'explore_site' not found in webprobe.explorer"
    assert callable(fn)
