"""Smoke tests for src/webprobe/mapper.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_mapper():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.mapper")
    assert mod is not None

def test_normalize_url_is_callable():
    """Function normalize_url exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.mapper")
    fn = getattr(mod, "normalize_url", None)
    assert fn is not None, "'normalize_url' not found in webprobe.mapper"
    assert callable(fn)

def test_is_same_origin_is_callable():
    """Function is_same_origin exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.mapper")
    fn = getattr(mod, "is_same_origin", None)
    assert fn is not None, "'is_same_origin' not found in webprobe.mapper"
    assert callable(fn)

def test_extract_links_is_callable():
    """Function extract_links exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.mapper")
    fn = getattr(mod, "extract_links", None)
    assert fn is not None, "'extract_links' not found in webprobe.mapper"
    assert callable(fn)

def test_parse_robots_txt_is_callable():
    """Function parse_robots_txt exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.mapper")
    fn = getattr(mod, "parse_robots_txt", None)
    assert fn is not None, "'parse_robots_txt' not found in webprobe.mapper"
    assert callable(fn)

def test_parse_sitemap_is_callable():
    """Function parse_sitemap exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.mapper")
    fn = getattr(mod, "parse_sitemap", None)
    assert fn is not None, "'parse_sitemap' not found in webprobe.mapper"
    assert callable(fn)

def test_map_site_is_callable():
    """Function map_site exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.mapper")
    fn = getattr(mod, "map_site", None)
    assert fn is not None, "'map_site' not found in webprobe.mapper"
    assert callable(fn)
