"""Smoke tests for src/webprobe/auth.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_auth():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.auth")
    assert mod is not None
