"""Smoke tests for src/webprobe/reporter.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_reporter():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.reporter")
    assert mod is not None

def test_generate_report_is_callable():
    """Function generate_report exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.reporter")
    fn = getattr(mod, "generate_report", None)
    assert fn is not None, "'generate_report' not found in webprobe.reporter"
    assert callable(fn)
