"""Smoke tests for src/webprobe/cli.py (auto-generated by pact adopt)."""

import pytest

def test_import_webprobe_cli():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in webprobe.cli"
    assert callable(fn)

def test_run_is_callable():
    """Function run exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    fn = getattr(mod, "run", None)
    assert fn is not None, "'run' not found in webprobe.cli"
    assert callable(fn)

def test_explore_cmd_is_callable():
    """Function explore_cmd exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    fn = getattr(mod, "explore_cmd", None)
    assert fn is not None, "'explore_cmd' not found in webprobe.cli"
    assert callable(fn)

def test_map_cmd_is_callable():
    """Function map_cmd exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    fn = getattr(mod, "map_cmd", None)
    assert fn is not None, "'map_cmd' not found in webprobe.cli"
    assert callable(fn)

def test_capture_is_callable():
    """Function capture exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    fn = getattr(mod, "capture", None)
    assert fn is not None, "'capture' not found in webprobe.cli"
    assert callable(fn)

def test_analyze_cmd_is_callable():
    """Function analyze_cmd exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    fn = getattr(mod, "analyze_cmd", None)
    assert fn is not None, "'analyze_cmd' not found in webprobe.cli"
    assert callable(fn)

def test_report_is_callable():
    """Function report exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    fn = getattr(mod, "report", None)
    assert fn is not None, "'report' not found in webprobe.cli"
    assert callable(fn)

def test_diff_is_callable():
    """Function diff exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    fn = getattr(mod, "diff", None)
    assert fn is not None, "'diff' not found in webprobe.cli"
    assert callable(fn)

def test_status_is_callable():
    """Function status exists and is callable."""
    import importlib
    mod = importlib.import_module("webprobe.cli")
    fn = getattr(mod, "status", None)
    assert fn is not None, "'status' not found in webprobe.cli"
    assert callable(fn)
